src/packet.rs

Perform the following name changes for `UtpPacketHeader`:
- rename `ts_microseconds` to `ts_micros`
- rename `ts_diff_microseconds` to `ts_diff_micros`

refactor: rename 'microseconds' fields to 'micros'

---

src/congestion.rs

Use more succinct naming in `congestion` module.

refactor: change naming in congestion module

---

Cargo.toml

Add `alpha` pre-release to crate version to mark instability.

add 'alpha' pre-release to version

---

src/lib.rs
src/seq.rs

Add a `seq` module to the crate for sequence number arithmetic/utilities.
Define `CircularRangeInclusive`, an inclusive range that supports wrapping around the maximum value.
Sequence number arithmetic is modulo `u16::MAX`. The `CircularRangeInclusive` struct will be used to determine whether a given packet contains a valid sequence number.

feat: add 'seq' module with circular inclusive range

---

src/congestion.rs

do not track timeouts internally in `congestion::Controller`
require the caller to register timeouts with congestion control through `on_timeout`

remove internal timeout tracking in congestion control

---

src/congestion.rs
src/lib.rs
src/sent.rs

add struct `SentPackets` to manage outgoing packets
* methods to account for transmissions and acknowledgements
* wraps congestion controller
* provides next sequence number
* provides current congestion timeout
* provides available send window
* manages lost packets

add sent packet management

---

src/recv.rs

box underlying array in receive buffer
* heap allocation for underlying array
* clone no longer duplicates the underlying array

box underlying array in receive buffer

---

src/conn.rs

change `transmit` from method to associated function of `Connection`
* pass in all necessary fields of connection so that transmission cannot fail
other: change `lost_packets` to `retransmit_lost_packets`, calling `transmit` if there are lost packets

refactor: change transmit method to associated function

---

Cargo.toml
src/lib.rs
src/socket.rs
src/udp.rs

define `AsyncUdpSocket` trait to abstract underlying transport
* add `async-trait` dependency
* implement `AsyncUdpSocket` for `tokio::net::UdpSocket`
* add `UtpSocket::with_socket` constructor that accepts `AsyncUdpSocket` implementor

add trait for UDP transport abstraction

---

src/cid.rs
src/conn.rs
src/socket.rs
src/stream.rs
src/udp.rs

define `ConnectionPeer` to represent a remote peer
make the following generic over `ConnectionPeer`:
* `ConnectionId`
* `ConnectionIdGenerator`
* `AsyncUdpSocket`
* `UtpSocket`
* `UtpStream`
* `Connection`

add trait for generic conn peer

---

src/stream.rs

change `io::ErrorKind` propagated to caller of `UtpStream` read/write
* if a read/write cannot be sent over the internal channel, then return `io::ErrorKind::NotConnected`
* if an error is returned by awaiting the internal channel, then propagate the error within `io::ErrorKind::Other`

refactor: change stream read/write IO error kind

---

src/socket.rs
tests/socket.rs

add methods to `UtpSocket` to connect/accept with a given `ConnectionId`
* add `connect_with_cid` method for `UtpSocket`
* add `accept_with_cid` method for `UtpSocket`
* fix non-propagated error in `connect` method of `UtpSocket`

add socket methods to connect/accept with given CID

---

src/conn.rs
src/event.rs
src/socket.rs
src/stream.rs

add `SocketEvent` enum with the following variants:
* `Outgoing`: transmit packet to peer
* `Shutdown`: notify socket that connection has shutdown

add socket event enum

---

src/socket.rs
tests/socket.rs

fix a bug where the socket would exit the event loop if a connection for a given connection ID (i.e. CID) was not available to accept. add a second connection to the crate-level test.

fix: 'continue' instead of 'return' for pending accept

---

src/cid.rs
src/socket.rs
src/stream.rs

add a parameter to the `cid` function of the `ConnectionIdGenerator` trait to denote whether to generate a CID for the initiating endpoint or the accepting endpoint.

modify CID generation fn to take endpoint flag

---

Cargo.toml

bump crate version to `0.1.0-alpha.1` so that we can increment post-alpha number to publish updates to `crates.io`

bump crate version to 0.1.0-alpha.1

---

Cargo.toml
src/congestion.rs
src/conn.rs

add the following congestion control parameters to `ConnectionConfig`:
* initial timeout
* minimum timeout
* target delay
other changes:
* change the default maximum packet size from 2048 to 1024
* expose some of the config defaults from the `congestion` module to the crate for use in the `conn` module
bump crate version from `0.1.0-alpha.1` to `0.1.0-alpha.2`

add congestion ctrl params to conn config

---

src/conn.rs
src/socket.rs

reduce log level for various `tracing` events
* `INFO` to `DEBUG`:
* connection start
* connection shutdown
* connection close
* `WARN` to `DEBUG`:
* receipt of packet for non-existing connection
* failure to send packet over socket

reduce log levels for various tracing events

---

Cargo.toml

bump version from `0.1.0-alpha.2` to `0.1.0-alpha.3`
changes:
* #40
* #41

bump version to 0.1.0-alpha.3

---

Cargo.toml
src/conn.rs

fixes:
* upon SYN-ACK, initialize the local ACK num to the sequence number in the SYN-ACK minus 1
* in `STATE` packets, set the sequence number to the next (unsent) sequence number
bump version to `0.1.0-alpha.4`

fix: ACK num initialization and STATE seq num

---

README.md

fixes https://github.com/ethereum/utp/issues/48
Emila asked me to make a PR for this. The warning is based off reth's warning, but with a minimal clear description.
Arguments for it are given in the issue linked above and during the call on 5/22/2023. If a library isn't stable it is good practice to give a warning regardless since you never know who will try to use it.

docs: add 'under construction' banner to README

---

src/congestion.rs
src/conn.rs

we have observed that the congestion control timeout can amplify quickly to the point where the timeout becomes not so useful. for example, the timeout should not exceed the maximum idle timeout.
summary:
* add a maximum timeout field to congestion control
* limit the number of timeouts registered with congestion control by the connection
* add a maximum timeout field to the connection config
* by default, this value is equal to the max idle timeout

limit congestion control timeout amplification

---

src/send.rs

available overflows in ``send.rs`` since the add for the offset is done after (I verified this testing local and this fixing it).
superedes https://github.com/ethereum/utp/pull/66 since the review process never got resolved, it has been 2 weeks without a response from pr 66's author, and this overflow bug is an annoying distraction well testing other problems so it would be nice to get it merged.

fix: reorder arithmetic in SendBuffer::available to prevent overflow

---

src/conn.rs

Split from #81 
Some discussion here: https://github.com/ethereum/utp/pull/81#discussion_r1234460457

bias conn event loop toward incoming packets and I/O

---

src/conn.rs

fix note about capping peer timestamp diff. the issue arises when the remote machine's clock is ahead of the local machine's, not the other way around.

docs: fix note about capping peer timestamp diff

---

src/socket.rs
tests/socket.rs

Useful for callers to get statistics on how many active connections are in flight. This is especially true since they need some awareness of the maximum number of connections in the configuration.

Add API to get the current number of connections

---

Cargo.toml
src/conn.rs
src/lib.rs
src/stream.rs
src/testutils.rs
tests/socket.rs
tests/stream.rs

Fix #89 
stream.close().await will not return until the connection exits, either from an error, or from all data being written and ACKed.
To simplify, `shutdown()` is no longer part of the public API.

Prefer close() to shutdown(), it waits for finish

---

src/conn.rs
tests/stream.rs

Split from #81 
- Catch a special case that doesn't need to be a warning: Dual FINs, all data ACKd
- set the Close status err to None
- log it at debug level only, it's not worth spamming the logs for
- Add a Debug formatter to the connection State
- Add state info to the idle timeout log
Optional extra:

Close without error, when only FIN-ACK is missing on timeout, and related logs

---

src/conn.rs
src/packet.rs

I added debug traces for "Write data"/"Received packet". Because when I am debugging it is hard to tell if nodes are even sending anything or receiving anything.
These longs are simliar to what fluffy/utp and bittorrent/libutp

Added tracing::trace!() for "Write data"/"Received packet"

---

src/conn.rs
tests/socket.rs
tests/stream.rs

Longer idle timeout has obvious effect of reducing connection failures due to idle timeout. This idle timeout doesn't seem to be specified anywhere in the main utp spec, we are just doing it. 10s seemed reasonable, but when trying to recover from a couple dropped packets, it gets less reasonable.
The retry timeout should be small enough that if it maxes out, there are a few chances at reattempts before the idle timeout. Setting it to /4 of the idle timeout means we should get at least 3 attempts (the 4th will race with the idle).
In high packet-drop scenarios, like 10%, then only making 3 attempts has a 1/1000 chance of failing the connection attempt. With 1000 transfers, the expected value of connection failures is about 1 per test.  By increasing to 5 attempts, the connection failures …

make default conn config more robust to packet drops

---

src/conn.rs

- By default, try up to 6 times instead of 5
- Retry after increasing timeout by 50% instead of 100%, which helps speed up the 6th attempt.
- Increase default connection timeout to 60s, to support 6th attempt
This is the last configuration change required to reliably pass the CI test with 2,000 concurrent connections.

feat: attempt connections a bit more aggressively

---

Cargo.toml
tests/socket.rs

This used to be a PR that grouped up all the changes needed to pass the high-concurrency tests. Now, with all the changes merged, the test is the only commit left, and it passes against master.
---
Previous writeup, for posterity
The minimal functional changes required to pass the high-volume socket test, plus some logs, pulled from #69 
The commits should be fairly clean to inspect individually, if you're into that kind of thing.
The functional changes are:
- Bias the connection event loop, to prefer handling inbound packets. Previously, it was possible to randomly choose to timeout a connection, even if an inbound packet was waiting on the queue.
- Use exponential backoff when sending SYN times out (the test tried a *bunch* of SYNs at once, exponential backoff helps recover from this …

test: run 2k concurrent transfers with 1MB of data

---

src/conn.rs
tests/socket.rs

A lot of the time I am debugging unless a connection fails there are no logs on information about the peer. This makes things hard because without this information I have no clue which uTP implementation I am looking at.

chore: add peer info to debug starting log

---

src/socket.rs
tests/stream.rs

```
thread 'tokio-runtime-worker' panicked at /usr/local/cargo/git/checkouts/utp-2d8a743206ecba20/6001fef/src/socket.rs:225:29:
internal error: entered unreachable code: Error awaiting_expirations should always contain valid awaiting items
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
This was caused by me double hashing the hashmap key.

fix: was double hashing hashmap key instead of single hashing

---

src/cid.rs

Cloning the Enr is very expensive. 
as seen from this graph
Hopefully we can lower this number in the future as a clone is still taking place, but this is better then nothing for now and signals the direction we are going in.

fix: remove non-need clone of peer

---

src/socket.rs

chore: fix typos

---

src/cid.rs
src/congestion.rs
src/socket.rs

In Trin we were calling `cid()` which was generating cids and putting them in a Hashset of other CIDs. The issue being this set was isolated and only used for generating cids. So if you accept content from a node enough times you would be stuck in a loop because old values would never be cleared, and there would never be a unique key which didn't exist so you would loop forever, trying to find a cid which didn't already exist. There also was no code to remove cid's from this hashset
This for one created a deadlock because the loop could never escape because a unique cid was impossible, but it also wasted tons of memory because the amount of times you inserted into the Hashset before you deadlocked was tied to the non-random variable aka the peer or in trins case the node id.
So 5 nodes …

fix: deadlock + memory leak caused by cid generation code

---

src/conn.rs

This is a flamegraph of trin's heap allocations
Around 85-90+% of our memory allocations look to be caused by uTP making non-needed clones 😱
I am going to do a quick refactor to fix this, but that is crazy
I would take the graph somewhat with a grain of salt because I had to strip some data from the profile to be able to read it as I don't have enough ram to load the full data unstripped
```
You can use the strip subcommand to strip away unnecessary allocations making it possible to load your data file for analysis even if you don't have enough RAM.
```
^ this is what the docs say
> strip away unnecessary allocations
I don't think this would make the result invalid though
As we can see from the picture Conn::shutdown() > clone is taking up like 70% of trins allocations
Combining the …

fix: stop cloning Connection::State as it is very wasteful

---

Makefile
src/conn.rs
tests/socket.rs

We support one way finalization's, fluffy had an `optimization` where it would read the data decode the length prefix of the `content value` and try to send an "early" Fin. This "early" Fin would only be sent 0.0001% of the time and it wouldn't acknowledge our Fin as well, so it caused us to timeout.
So we will assume if they send us a pre-mature Fin after we sent our Fin that they are trying to close early and already got the data.
- Kim from Fluffy said they would remove this "early" Fin, as in practice it doesn't improve close times, but can make it work.
But we still need to be able to handle it in the cause someone sends us a malformed flow or something.
Because we use the One way Finalization model, only 1 Fin should ever be sent in total during any transmission. So if there is a …

fix: handle one-way fin edge case

---

src/recv.rs

I am benchmarking trin and I noticed, (this was happening in the wild, but there wasn't a reliable way to reproduce it until now)
```
trin-receiver-1              | 2025-01-28T19:37:56.268774Z  WARN discv5::socket::send: Sending packet larger than max size size=8325 max=1280
trin-receiver-1              | 2025-01-28T19:37:56.268803Z  WARN discv5::socket::send: Sending packet larger than max size size=8325 max=1280
trin-sender-1                | 2025-01-28T19:37:56.268857Z  WARN discv5::handler: Session is not established. Dropping response response=Response: id: 7f6ca4f562dd0902: Response: Response  node=0xee0d..5fa4
trin-receiver-1              | 2025-01-28T19:37:56.268818Z  WARN discv5::socket::send: Sending packet larger than max size size=8325 max=1280
```
We were trying to send …

fix: selective ack construction breaks on overflow

---

.circleci/config.yml
src/cid.rs
src/conn.rs
src/event.rs
src/lib.rs
src/peer.rs
src/socket.rs
src/stream.rs
src/testutils.rs
src/udp.rs
tests/socket.rs
tests/stream.rs

This PR allows `ConnectionPeer` to expose `PeerId` type and merge function.
This allows utp library to not require Peer object itself, but only PeerId object.
If multiple peer objects are provided for the same connection, they will be merged together and passed during `AsyncUdpSocket::send_to`.
The https://github.com/ethereum/trin/pull/1652 exposes how this works within trin client.
Note: I updated circleci rust version to 1.81.0 because old version was complaining about "Associated type bounds" syntax [`P: ConnectionPeer<Id: Unpin> + Unpin + 'static`](https://github.com/ethereum/utp/blob/16087be7139fc9827741cc4f23fdca061252bf50/src/socket.rs#L63)

feat!: distinguish peer and peer_id on api level
