ethereum/utp

.circleci/config.yml
src/packet.rs

Add initial configuration file for Circle CI. Fix outstanding `clippy` warning.

ci: add Circle CI config

---

src/lib.rs
src/send.rs

add initial send buffer `SendBuffer`
* fixed-size buffer
* produces data payloads based on previous writes and given buffer

add send buffer

---

src/packet.rs

add `PacketBuilder` to aid construction and/or alteration of `Packet`
* builder pattern for `Packet`
* conversion of `Packet` to `PacketBuilder`

add builder pattern for packet

---

src/cid.rs
src/conn.rs
src/lib.rs

define `ConnectionId` struct and `ConnectionIdGenerator` trait
* define trait for connection ID generation for extensibility
* define standard connection ID generator according to uTP spec

add conn ID and conn ID generator

---

src/conn.rs
src/sent.rs

make `congestion::Controller` configurable by the constructor of `SentPackets`
* congestion control should be configurable at the connection and socket level

refactor: make congestion ctrl arg of sent packets constructor

---

src/congestion.rs

remove `DuplicateAck` error from congestion control
* make a duplicate acknowledgement a no-op

remove duplicate ack error from congestion ctrl

---

src/recv.rs
src/send.rs

add `is_empty` method to `SendBuffer` and `ReceiveBuffer`

add 'is_empty' method to send & receive buffers

---

src/congestion.rs

* use saturating arithmetic for the following computations:
* available window based on difference of max window and bytes in flight
* adjusted max window based on current max window and max window increment
* use a comparison to keep adjusted max window at or above minimum window instead of merely non-negative

fix: congestion control arithmetic

---

Cargo.toml
src/conn.rs
src/socket.rs
src/stream.rs
tests/socket.rs

add initial instrumentation via `tracing` crate

add initial logging/tracing

---

src/conn.rs

various fixes and enhancements:
* change default max packet size from 2048 to 1024
* add a max idle timeout with a default value of 10 seconds
* if the timeout expires, then close the connection with a timeout error
* if the connection represents the accepting endpoint, then mark the connection established after the SYN-ACK is sent
* enable the accepting endpoint to send `DATA` without receiving `DATA` from the initiating endpoint
* transmit the `FIN` so that its sequence number is recorded and tracked for acknowledgement
* if a `SYN` times out after the connection moves beyond the `Connecting` state, then do nothing
* cap the peer timestamp difference, which may appear very large if the packet timestamp is behind the current local timestamp
* process pending reads upon receipt of a `FIN` …

fix: various fixes/enhancements to conn

---

README.md

add a basic usage example to the `README.md`

add basic usage example to README

---

README.md
src/socket.rs
tests/socket.rs

add a `ConnectionConfig` parameter to the following `UtpSocket` methods:
* `accept`
* `accept_with_cid`
* `connect`
* `connect_with_cid`

add conn config param to accept/connect methods

---

src/conn.rs

emit an event at `WARN` level when the connection is reset
* implement `fmt::Display` for `conn::Error`
* log the error both as a structured field and as a part of the log message

emit warning log for connection reset

---

src/socket.rs

Split off from #81 
This helps handle high-stress situations, by minimizing packet loss. If incoming packets overflow the UDP buffer, then they will be dropped. Too many dropped packets messes up the transfer, and causes failures in our high-stress socket test.
Naturally, this will mean that we delay more outgoing packets, for longer. UTP nicely handles this situation, by reducing the transfer window size, to lower the throughput, and back off sending so much.
Pairing this with earlier changes, and the upcoming limit of concurrent outbound connections, is enough to reliably pass the high-stress socket tests in my local tests.

bias socket event loop toward reading from UDP

---

src/conn.rs
src/socket.rs

Outgoing connection exponential backoff

---

src/conn.rs

Split from #81 
Error will always be the same type, no need to log it.
Other conversation: https://github.com/ethereum/utp/pull/81#discussion_r1234472553
Ideally, we would detect somehow that it was a normal shutdown, and we would just silently exit. But if it happens at a surprising time, then it is valuable to have the log. Warn seems like about the right level for that, especially since it typically doesn't trigger very often.

Log error, don't crash, if socket closes mid-send

---

src/conn.rs

It's treated the same as non-empty data, so get rid of all the branch handling.

refactor: don't wrap empty fin data in Option

---

src/conn.rs
src/sent.rs

Fix #103
Two changes:
- refactor to make the next change easier (remove an unnecessary Option)
- **Main Change**: acknowledge sent packets using `ack_num` in FIN and DATA packets
More details on main change:
The ack_nr on the received packet was previously ignored. In some scenarios, like with dropped packets or different utp implementations, that would cause the sender to wait indefinitely for the recipient to ACK state. But the recipient had already acked with the FIN (been ignored), and disconnected. Then the sender was waiting the full connection timeout to realize it.
Even worse, if more than just the final outbound FIN was acknowledged in the inbound FIN, the sender was considering the data transfer incomplete. This was causing errors in #81 .
With this commit:
- When the recipient …

Acknowledge sent packets when receiving a FIN

---

src/conn.rs

Some reattempts are normal, so slowly ramp up the log level as the number of attempts increases.

feat: logs connection reattempts

---

src/socket.rs

We are missing the 3rd case a reset can have in our code. Here is how the standard library handles it
https://github.com/bittorrent/libutp/blob/2b364cbb0650bdab64a5de2abb4518f9f228ec44/utp_internal.cpp#L2850-L2859
```
// id is either our recv id or our send id
// if it's our send id, and we initiated the connection, our recv id is id + 1
// if it's our send id, and we did not initiate the connection, our recv id is id - 1
// we have to check every case
```
With this change we handle Fluffy's resets where before we ignored them till the timeout ranout. The 2 logs below are showing the issue before this PR
```nim
2023-09-23T23:24:13.777799Z TRACE uTP{send=23953 recv=23952}: utp_rs::conn: Received packet cid=23952 packetType=ST_DATA seqNr=47990 ackNr=44195 timestamp=2613482883 …
```

Fix to stop resending after connection is closed

---

src/socket.rs

fixes https://github.com/ethereum/utp/issues/123
Also I clean up my last PR.
ConnectionId<> can't be used in HashMapDelay or HashMapDelay because its trait constraints P can't support streams. Why is this? UdpSocket

fix: timeout stale incoming_conns + clean up last PR

---

src/conn.rs
tests/socket.rs

@njgheorghita this is the fix for the 1MiB transfer failures you were seeing in the "gossip on delete" prototype.
Problem: transfers with single writes over ~1MB were hanging, then failing by timeout.
Basic approach:
- First, I refactored the existing concurrency test so that we can pass in custom data values (like a single larger value)
- Second, I added a test that sends a large value. I could trigger the failure with 1024^2 + 1 bytes, while one fewer byte passes the test. It seemed worth testing a much larger amount, so I went up to 50 MiB successfully. I ran into issues at 100MiB that might be related to a rollover at 2^16 packets, but punted on that for now.
- Third, I fixed the bug (and passed the test) by splitting up pending writes when they don't fit in the buffer. This also …

Fix large transfers

---

src/socket.rs

Currently we are using HashMap+HashSetDelay combination for tracking accepted and incoming connection.
This PR simplifies it by using HashMapDelay instead.

refactor: use HashMapDelay for awaiting and incoming connections
